# Loss or Cost Function (For better understanding how it works)

#### The loss function is to capture the difference between the actual and predicted values for a single record whereas cost functions aggregate the difference for the entire training dataset. The Most commonly used loss functions are Mean-squared error and Hinge loss.

In [1]:
import numpy as np

In [7]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

## Implement Mean Absolute Error

In [10]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt ,yp in zip(y_true,y_predicted):
        print(yt,yp)

In [11]:
mae(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [25]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt ,yp in zip(y_true,y_predicted):
        total_error +=abs(yt - yp)
        mean = total_error /len(y_true)
        print("Total Error : ",total_error)
        print("MAE : ",mean)

In [26]:
mae(y_true,y_predicted)

Total Error :  0.7
MAE :  0.13999999999999999
Total Error :  1.0
MAE :  0.2
Total Error :  2.0
MAE :  0.4
Total Error :  2.0
MAE :  0.4
Total Error :  2.5
MAE :  0.5


## Implement same thing using numpy in much easier way

In [28]:
np.abs(y_true - y_predicted)

array([0.7, 0.3, 1. , 0. , 0.5])

In [27]:
np.mean(np.abs(y_true - y_predicted))

0.5

## Implement Log Loss or Binary Cross Entropy

In [35]:
# here will convert 1 ---> the no. close to one -->0.99999999 and 0 -->0.0000000001

epsilon = 1e-15
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [36]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [37]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [43]:
y_predicted_new_1=np.array(y_predicted_new)

In [44]:
-np.mean(y_true*np.log(y_predicted_new_1)+(1-y_true)*np.log(1-y_predicted_new_1))

17.2696280766844

In [45]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new_1 = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new_1)+(1-y_true)*np.log(1-y_predicted_new_1))
log_loss(y_true, y_predicted)

17.2696280766844

### Exercise
#### • Implement mean squared error (or MSE) in two ways,

#### 1) Without using numpy (i.e. using plain python)

#### 2) With the use of numpy

In [52]:
# Implement mean squared error (or MSE) in two ways,
def mse(y_true,y_predicted):
    total_error = 0
    for yt ,yp in zip(y_true,y_predicted):
        total_error +=abs(yt - yp)**2 #----> x^2
        mean_squared = total_error /len(y_true)
        print("Total Error : ",total_error)
        print("MAE : ",mean_squared)


In [53]:
mse(y_true,y_predicted)

Total Error :  0.48999999999999994
MAE :  0.09799999999999999
Total Error :  0.58
MAE :  0.11599999999999999
Total Error :  1.58
MAE :  0.316
Total Error :  1.58
MAE :  0.316
Total Error :  1.83
MAE :  0.366


## MSE using numpy

In [54]:
np.abs(y_true - y_predicted)

array([0.7, 0.3, 1. , 0. , 0.5])

In [55]:
np.mean(np.abs(y_true - y_predicted)**2)

0.366